# Generated by Django 4.2.1 on 2023-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_course_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
