# Generated by Django 4.2.1 on 2023-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0004_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursesyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('day', models.IntegerField()),
                ('syllabus', models.CharField(max_length=200)),
                ('percentage', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Course Syllabus',
            },
        ),
    ]
