# Generated by Django 4.2.1 on 2023-07-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0006_delete_coursesyllabus_delete_day_delete_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='Days')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
