# Generated by Django 4.2.1 on 2023-07-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0008_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursesyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=200)),
                ('Course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.course')),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.day')),
                ('syllabus', models.ManyToManyField(to='tracker_app.syllabus')),
            ],
            options={
                'verbose_name_plural': 'Course Syllabus',
            },
        ),
    ]
